/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "split.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

int *
inscription_1(utilisateur *argp, CLIENT *clnt)
{
	static int clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, INSCRIPTION,
		(xdrproc_t) xdr_utilisateur, (caddr_t) argp,
		(xdrproc_t) xdr_int, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

int *
desinscription_1(utilisateur *argp, CLIENT *clnt)
{
	static int clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, DESINSCRIPTION,
		(xdrproc_t) xdr_utilisateur, (caddr_t) argp,
		(xdrproc_t) xdr_int, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

utilisateur *
add_abonnement_1(gestion_abonnement *argp, CLIENT *clnt)
{
	static utilisateur clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, ADD_ABONNEMENT,
		(xdrproc_t) xdr_gestion_abonnement, (caddr_t) argp,
		(xdrproc_t) xdr_utilisateur, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

utilisateur *
remove_abonnement_1(gestion_abonnement *argp, CLIENT *clnt)
{
	static utilisateur clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, REMOVE_ABONNEMENT,
		(xdrproc_t) xdr_gestion_abonnement, (caddr_t) argp,
		(xdrproc_t) xdr_utilisateur, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

int *
propose_partage_abonnement_1(partage_abonnement *argp, CLIENT *clnt)
{
	static int clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, PROPOSE_PARTAGE_ABONNEMENT,
		(xdrproc_t) xdr_partage_abonnement, (caddr_t) argp,
		(xdrproc_t) xdr_int, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

int *
cancel_partage_abonnement_1(partage_abonnement *argp, CLIENT *clnt)
{
	static int clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, CANCEL_PARTAGE_ABONNEMENT,
		(xdrproc_t) xdr_partage_abonnement, (caddr_t) argp,
		(xdrproc_t) xdr_int, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

partage_abonnement *
search_partage_abonnement_1(search *argp, CLIENT *clnt)
{
	static partage_abonnement clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, SEARCH_PARTAGE_ABONNEMENT,
		(xdrproc_t) xdr_search, (caddr_t) argp,
		(xdrproc_t) xdr_partage_abonnement, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

int *
select_partage_abonnement_1(select_partage *argp, CLIENT *clnt)
{
	static int clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, SELECT_PARTAGE_ABONNEMENT,
		(xdrproc_t) xdr_select_partage, (caddr_t) argp,
		(xdrproc_t) xdr_int, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

int *
cancel_co_abonnement_1(select_partage *argp, CLIENT *clnt)
{
	static int clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, CANCEL_CO_ABONNEMENT,
		(xdrproc_t) xdr_select_partage, (caddr_t) argp,
		(xdrproc_t) xdr_int, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

int *
add_evaluation_1(note *argp, CLIENT *clnt)
{
	static int clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, ADD_EVALUATION,
		(xdrproc_t) xdr_note, (caddr_t) argp,
		(xdrproc_t) xdr_int, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

int *
connect_utilisateur_1(utilisateur *argp, CLIENT *clnt)
{
	static int clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, CONNECT_UTILISATEUR,
		(xdrproc_t) xdr_utilisateur, (caddr_t) argp,
		(xdrproc_t) xdr_int, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

utilisateur *
update_utilisateur_1(utilisateur *argp, CLIENT *clnt)
{
	static utilisateur clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, UPDATE_UTILISATEUR,
		(xdrproc_t) xdr_utilisateur, (caddr_t) argp,
		(xdrproc_t) xdr_utilisateur, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
