/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "split.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static void
splitprog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		utilisateur inscription_1_arg;
		utilisateur desinscription_1_arg;
		gestion_abonnement add_abonnement_1_arg;
		gestion_abonnement remove_abonnement_1_arg;
		partage_abonnement propose_partage_abonnement_1_arg;
		partage_abonnement cancel_partage_abonnement_1_arg;
		search search_partage_abonnement_1_arg;
		select_partage select_partage_abonnement_1_arg;
		select_partage cancel_co_abonnement_1_arg;
		note add_evaluation_1_arg;
		utilisateur connect_utilisateur_1_arg;
		utilisateur update_utilisateur_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case INSCRIPTION:
		_xdr_argument = (xdrproc_t) xdr_utilisateur;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) inscription_1_svc;
		break;

	case DESINSCRIPTION:
		_xdr_argument = (xdrproc_t) xdr_utilisateur;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) desinscription_1_svc;
		break;

	case ADD_ABONNEMENT:
		_xdr_argument = (xdrproc_t) xdr_gestion_abonnement;
		_xdr_result = (xdrproc_t) xdr_utilisateur;
		local = (char *(*)(char *, struct svc_req *)) add_abonnement_1_svc;
		break;

	case REMOVE_ABONNEMENT:
		_xdr_argument = (xdrproc_t) xdr_gestion_abonnement;
		_xdr_result = (xdrproc_t) xdr_utilisateur;
		local = (char *(*)(char *, struct svc_req *)) remove_abonnement_1_svc;
		break;

	case PROPOSE_PARTAGE_ABONNEMENT:
		_xdr_argument = (xdrproc_t) xdr_partage_abonnement;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) propose_partage_abonnement_1_svc;
		break;

	case CANCEL_PARTAGE_ABONNEMENT:
		_xdr_argument = (xdrproc_t) xdr_partage_abonnement;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) cancel_partage_abonnement_1_svc;
		break;

	case SEARCH_PARTAGE_ABONNEMENT:
		_xdr_argument = (xdrproc_t) xdr_search;
		_xdr_result = (xdrproc_t) xdr_partage_abonnement;
		local = (char *(*)(char *, struct svc_req *)) search_partage_abonnement_1_svc;
		break;

	case SELECT_PARTAGE_ABONNEMENT:
		_xdr_argument = (xdrproc_t) xdr_select_partage;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) select_partage_abonnement_1_svc;
		break;

	case CANCEL_CO_ABONNEMENT:
		_xdr_argument = (xdrproc_t) xdr_select_partage;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) cancel_co_abonnement_1_svc;
		break;

	case ADD_EVALUATION:
		_xdr_argument = (xdrproc_t) xdr_note;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) add_evaluation_1_svc;
		break;

	case CONNECT_UTILISATEUR:
		_xdr_argument = (xdrproc_t) xdr_utilisateur;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) connect_utilisateur_1_svc;
		break;

	case UPDATE_UTILISATEUR:
		_xdr_argument = (xdrproc_t) xdr_utilisateur;
		_xdr_result = (xdrproc_t) xdr_utilisateur;
		local = (char *(*)(char *, struct svc_req *)) update_utilisateur_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (SPLITPROG, SPLITVERS);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, SPLITPROG, SPLITVERS, splitprog_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (SPLITPROG, SPLITVERS, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, SPLITPROG, SPLITVERS, splitprog_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (SPLITPROG, SPLITVERS, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
