/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "split.h"


void
splitprog_1(char *host)
{
	CLIENT *clnt;
	int  *result_1;
	utilisateur  inscription_1_arg;
	int  *result_2;
	utilisateur  desinscription_1_arg;
	utilisateur  *result_3;
	gestion_abonnement  add_abonnement_1_arg;
	utilisateur  *result_4;
	gestion_abonnement  remove_abonnement_1_arg;
	int  *result_5;
	partage_abonnement  propose_partage_abonnement_1_arg;
	int  *result_6;
	partage_abonnement  cancel_partage_abonnement_1_arg;
	partage_abonnement  *result_7;
	search  search_partage_abonnement_1_arg;
	int  *result_8;
	select_partage  select_partage_abonnement_1_arg;
	int  *result_9;
	select_partage  cancel_co_abonnement_1_arg;
	int  *result_10;
	note  add_evaluation_1_arg;
	int  *result_11;
	utilisateur  connect_utilisateur_1_arg;
	utilisateur  *result_12;
	utilisateur  update_utilisateur_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, SPLITPROG, SPLITVERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	void print_utilisateur(utilisateur u) {
		printf("id: %d\t nom: %s\t email: %s\t adresse: %s\n", u.id, u.nom, u.email, u.adresse);
	}

	// INSCRIPTION 
	printf("\n******************INSCRIPTION***********************\n");
	
		//USER 1
	strcpy(inscription_1_arg.nom, "Eric");
	strcpy(inscription_1_arg.email, "eric.lefebvre@etudiant.univ-brest.fr");
	strcpy(inscription_1_arg.adresse, "42 rue Albert Louppe");
	//inscription_1_arg.nb_abo = 0;
	
	result_1 = inscription_1(&inscription_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "Echec de l'inscription");
	}
	
	if (*result_1 == -1) {
		printf("L'utilisateur n'a pas pu etre ajoute\n");
	}
	else {
		inscription_1_arg.id = *result_1;
		printf("Utilisateur ajoute:\n");
		print_utilisateur(inscription_1_arg);
	}

	utilisateur user1 = inscription_1_arg;

		//USER 2
	strcpy(inscription_1_arg.nom, "Victor");
	strcpy(inscription_1_arg.email, "victor.quilgars@etudiant.univ-brest.fr");
	strcpy(inscription_1_arg.adresse, "20 rue des Salles");
	//inscription_1_arg.nb_abo = 0;
	
	result_1 = inscription_1(&inscription_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "Echec de l'inscription");
	}

	if (*result_1 == -1) {
		printf("Erreur lors de l'inscription\n");
	}
	else {
		inscription_1_arg.id = *result_1;
		printf("Utilisateur ajoute:\n");
		print_utilisateur(inscription_1_arg);
	}

	utilisateur user2 = inscription_1_arg;
	
		//USER 3
	strcpy(inscription_1_arg.nom, "Francis");
	strcpy(inscription_1_arg.email, "francis.cabrel@etudiant.univ-brest.fr");
	strcpy(inscription_1_arg.adresse, "Camargue");
	//inscription_1_arg.nb_abo = 0;
	
	result_1 = inscription_1(&inscription_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "Echec de l'inscription");
	}

	if (*result_1 == -1) {
		printf("Erreur lors de l'inscription\n");
	}
	else {
		inscription_1_arg.id = *result_1;
		printf("Utilisateur ajoute:\n");
		print_utilisateur(inscription_1_arg);
	}

	utilisateur user3 = inscription_1_arg;

	// DESINSCRIPTION
	printf("\n******************DESINSCRIPTION***********************\n");
	
	desinscription_1_arg = user3;
	
	result_2 = desinscription_1(&desinscription_1_arg, clnt);
	if (result_2 == (int *) NULL) {
		clnt_perror (clnt, "Echec de la desinscription");
	}
	
	if (*result_2 == -1) {
		printf("Erreur lors de la desinscription\n");
	} else {
		printf("Utilisateur desinscrit:\n");
		print_utilisateur(inscription_1_arg);
	}
	
	// ADD ABONNEMENT
	printf("\n******************ADD ABONNEMENT***********************\n");
		//Abonnement 1
	add_abonnement_1_arg.user = user1;
	abonnement abo1;
	abo1.id = 1;
	strcpy(abo1.nom, "Netflix");
	abo1.prix = 5;
	add_abonnement_1_arg.abo = abo1;
	
	result_3 = add_abonnement_1(&add_abonnement_1_arg, clnt);
	if (result_3 == (utilisateur *) NULL) {
		clnt_perror (clnt, "Echec de l'ajout d'abonnement");
	}

		//mise a jour de l'utilisateur avec sa nouvelle liste d'abonnements
	add_abonnement_1_arg.user = *result_3;
	
	printf("Abonnement ajoute:\n");
	printf("Id utilisateur: %d, Nombre d'abonnements: %d\nId abonnement: %d, Nom abonnement: %s\n", 
		add_abonnement_1_arg.user.id, add_abonnement_1_arg.user.nb_abo, add_abonnement_1_arg.user.liste_abo[0].id, add_abonnement_1_arg.user.liste_abo[0].nom);
	
		//Abonnement 2
	abonnement abo2;
	abo2.id = 2;
	strcpy(abo2.nom, "Canal");
	abo2.prix = 10;
	add_abonnement_1_arg.abo = abo2;
	
	result_3 = add_abonnement_1(&add_abonnement_1_arg, clnt);
	if (result_3 == (utilisateur *) NULL) {
		clnt_perror (clnt, "Echec de l'ajout d'abonnement");
	}

		//mise a jour de l'utilisateur avec sa nouvelle liste d'abonnements
	add_abonnement_1_arg.user = *result_3;
	
	printf("Abonnement ajoute:\n");
	printf("Id utilisateur: %d, Nombre d'abonnements: %d\nId abonnement: %d, Nom abonnement: %s\n", 
		add_abonnement_1_arg.user.id, add_abonnement_1_arg.user.nb_abo, add_abonnement_1_arg.user.liste_abo[1].id, add_abonnement_1_arg.user.liste_abo[1].nom);

	// REMOVE ABONNEMENT
	printf("\n******************REMOVE ABONNEMENT***********************\n");
	
	remove_abonnement_1_arg = add_abonnement_1_arg;
	
	result_4 = remove_abonnement_1(&remove_abonnement_1_arg, clnt);
	if (result_4 == (utilisateur *) NULL) {
		clnt_perror (clnt, "Echec de la suppression d'abonnement");
	}
	
	remove_abonnement_1_arg.user = *result_4;
	
	printf("Abonnement retire:\n");
	printf("Nom utilisateur: %s, Nouvelle liste d'abonnements:\n", 
	remove_abonnement_1_arg.user.nom);
	for (int i = 0; remove_abonnement_1_arg.user.liste_abo[i].id != 0; i++) {
		printf("Abonnement a %s au prix de %d euros\n", 
		remove_abonnement_1_arg.user.liste_abo[i].nom, remove_abonnement_1_arg.user.liste_abo[i].prix);
	}
	
	// PROPOSE PARTAGE
	printf("\n******************PROPOSE PARTAGE***********************\n");
	
		//partage 1
	offre offre_partage1;
	offre_partage1.id = 1;
	offre_partage1.abo = abo1;
	offre_partage1.prix_partage = 2.00;
	
	propose_partage_abonnement_1_arg.user = *result_4;
	propose_partage_abonnement_1_arg.partage = offre_partage1;
	
	result_5 = propose_partage_abonnement_1(&propose_partage_abonnement_1_arg, clnt);
	if (result_5 == (int *) NULL) {
		clnt_perror (clnt, "Echec de la proposition de partage");
	}
	
	if (*result_5 == -1) {
		printf("Erreur lors de la proposition de partage\n");
	} else {
		printf("Partage propose:\n");
		printf("Id partage: %d, %s partage son abonnement a %s au prix de %.2f euros\n",
		propose_partage_abonnement_1_arg.partage.id, propose_partage_abonnement_1_arg.user.nom, propose_partage_abonnement_1_arg.partage.abo.nom, propose_partage_abonnement_1_arg.partage.prix_partage);
	}
	
		//partage 2
	offre offre_partage2;
	offre_partage2.id = 2;
	offre_partage2.abo = abo1;
	offre_partage2.prix_partage = 4.00;
	
	propose_partage_abonnement_1_arg.user = *result_4;
	propose_partage_abonnement_1_arg.partage = offre_partage2;
	
	result_5 = propose_partage_abonnement_1(&propose_partage_abonnement_1_arg, clnt);
	if (result_5 == (int *) NULL) {
		clnt_perror (clnt, "Echec de la proposition de partage");
	}
	
	if (*result_5 == -1) {
		printf("Erreur lors de la proposition de partage\n");
	} else {
		printf("Partage propose:\n");
		printf("Id partage: %d, %s partage son abonnement a %s au prix de %.2f euros\n",
		propose_partage_abonnement_1_arg.partage.id, propose_partage_abonnement_1_arg.user.nom, propose_partage_abonnement_1_arg.partage.abo.nom, propose_partage_abonnement_1_arg.partage.prix_partage);
	}
	
	// CANCEL PARTAGE
	printf("\n******************CANCEL PARTAGE***********************\n");
	
	cancel_partage_abonnement_1_arg = propose_partage_abonnement_1_arg;
	
	result_6 = cancel_partage_abonnement_1(&cancel_partage_abonnement_1_arg, clnt);
	if (result_6 == (int *) NULL) {
		clnt_perror (clnt, "Echec de l'annulation de partage");
	}
	
	if (*result_6 == -1) {
		printf("Erreur lors de l'annulation du partage");
	} else {
		printf("Partage annule:\n");
		printf("%s annule sa proposition de partage a son abonnement a %s\n",
		cancel_partage_abonnement_1_arg.user.nom, cancel_partage_abonnement_1_arg.partage.abo.nom);
	}
	
	// SEARCH PARTAGE
	printf("\n******************SEARCH PARTAGE***********************\n");
	
	strcpy(search_partage_abonnement_1_arg.nom, "Netflix");
	search_partage_abonnement_1_arg.prix_max = 20;
	
	result_7 = search_partage_abonnement_1(&search_partage_abonnement_1_arg, clnt);
	if (result_7 == (partage_abonnement *) NULL) {
		clnt_perror (clnt, "Echec de la recherche de partage");
	}
	
	partage_abonnement resultat_recherche = *result_7;
	
	printf("Partage trouve:\n");
	printf("Nom: %s, Prix: %.2f\n", resultat_recherche.partage.abo.nom, resultat_recherche.partage.prix_partage);
	
	// SELECT PARTAGE
	printf("\n******************SELECT PARTAGE***********************\n");
	
	select_partage_abonnement_1_arg.user = user2;
	select_partage_abonnement_1_arg.selectionne = resultat_recherche;
	
	result_8 = select_partage_abonnement_1(&select_partage_abonnement_1_arg, clnt);
	if (result_8 == (int *) NULL) {
		clnt_perror (clnt, "Echec de la selection du partage");
	}
	
	if (*result_8 == -1) {
		printf("Erreur lors de la selection du partage\n");
	} else {
		printf("Partage selectionne:\n");
		printf("Utilisateur: %s, Nom: %s, Prix: %.2f\n",
		select_partage_abonnement_1_arg.user.nom, select_partage_abonnement_1_arg.selectionne.partage.abo.nom,
		select_partage_abonnement_1_arg.selectionne.partage.prix_partage);
	}
	
	// CANCEL COABONNEMENT
	printf("\n******************CANCEL COABONNEMENT***********************\n");
	
	cancel_co_abonnement_1_arg = select_partage_abonnement_1_arg;
	
	result_9 = cancel_co_abonnement_1(&cancel_co_abonnement_1_arg, clnt);
	if (result_9 == (int *) NULL) {
		clnt_perror (clnt, "Echec de l'annulation du co-abonnement");
	}
	
	if (*result_9 == -1) {
		printf("Erreur lors de l'annulation du co-abonnement\n");
	} else {
		printf("Co-abonnement annule:\n");
		printf("Utilisateur: %s, Nom: %s, Prix: %.2f\n",
		cancel_co_abonnement_1_arg.user.nom, cancel_co_abonnement_1_arg.selectionne.partage.abo.nom,
		cancel_co_abonnement_1_arg.selectionne.partage.prix_partage);
	}
	
	// ADD EVALUATION
	printf("\n******************ADD EVALUATION***********************\n");
	
	evaluation eval1;
	eval1.id = 1;
	eval1.user = user2;
	eval1.note = 5;
	strcpy(eval1.commentaire, "C'est super !");
	add_evaluation_1_arg.id = 1;
	add_evaluation_1_arg.eval = eval1;
	add_evaluation_1_arg.user = user1;
	
	result_10 = add_evaluation_1(&add_evaluation_1_arg, clnt);
	if (result_10 == (int *) NULL) {
		clnt_perror (clnt, "Echec de l'ajout de la note");
	}
	
	if (*result_10 == -1) {
		printf("Erreur lors de l'ajout de la note\n");
	} else {
		printf("Evaluation ajoutee:\n");
		printf("Evaluateur: %s, Note: %d, Evalue: %s\n",
		add_evaluation_1_arg.eval.user.nom, add_evaluation_1_arg.eval.note,
		add_evaluation_1_arg.user.nom);
	}

	// CONNECT UTILISATEUR
	printf("\n******************CONNECT UTILISATEUR***********************\n");
	
	connect_utilisateur_1_arg = user1;
	
	result_11 = connect_utilisateur_1(&connect_utilisateur_1_arg, clnt);
	if (result_11 == (int *) NULL) {
		clnt_perror (clnt, "Echec de la connexion");
	}
	
	if (*result_11 == -1) {
		printf("Erreur lors de la connexion\n");
	} else {
		printf("Connexion réussie: id: %d\n", *result_11);
	}
	
	printf("\n******************UPDATE UTILISATEUR***********************\n");

	update_utilisateur_1_arg = user2;
	result_12 = update_utilisateur_1(&update_utilisateur_1_arg, clnt);
	if (result_12 == (utilisateur *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	
	if(result_12->id == 0){
		printf("Erreur update\n");
	}
	else{
		printf("Update réussie\n");
		print_utilisateur(*result_12);
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	splitprog_1 (host);
exit (0);
}
